name: collaborative_shopping_list
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  get: ^4.6.6
  cupertino_icons: ^1.0.8
  flutter_stripe: ^10.0.0  # Added for Stripe payment integration
  http: ^1.1.0            # Added for making HTTP requests to backend

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true