// File generated by FlutterFire CLI (manually adjusted).
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ0PSfTzFNKLz_0Vfy5o8FBk4UhTMfNL0', // Use consistent API key
    appId: '1:634789103287:web:a118bbd44ad45f6f046f32',
    messagingSenderId: '634789103287',
    projectId: 'shoppinglistapp-9a3df',
    authDomain: 'shoppinglistapp-9a3df.firebaseapp.com',
    storageBucket: 'shoppinglistapp-9a3df.firebasestorage.app',
    measurementId: 'G-9YY1RM8GVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '', // Replace with key from google-services.json
    appId: '1:634789103287:android:44d5c1c29000f923046f32',
    messagingSenderId: '634789103287',
    projectId: 'shoppinglistapp-9a3df',
    storageBucket: 'shoppinglistapp-9a3df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ0PSfTzFNKLz_0Vfy5o8FBk4UhTMfNL0', // Matches GoogleService-Info.plist
    appId: '1:634789103287:ios:fdc067d6b8b469aa046f32',
    messagingSenderId: '634789103287',
    projectId: 'shoppinglistapp-9a3df',
    storageBucket: 'shoppinglistapp-9a3df.firebasestorage.app',
    iosBundleId: 'com.example.collaborativeShoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ0PSfTzFNKLz_0Vfy5o8FBk4UhTMfNL0', // Use consistent API key
    appId: '1:634789103287:macos:YOUR_MACOS_APP_ID', // Replace with valid macOS app ID
    messagingSenderId: '634789103287',
    projectId: 'shoppinglistapp-9a3df',
    storageBucket: 'shoppinglistapp-9a3df.firebasestorage.app',
    iosBundleId: 'com.example.collaborativeShoppingList.macos', // Adjust if needed
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJ0PSfTzFNKLz_0Vfy5o8FBk4UhTMfNL0', // Use consistent API key
    appId: '1:634789103287:windows:YOUR_WINDOWS_APP_ID', // Replace with valid Windows app ID
    messagingSenderId: '634789103287',
    projectId: 'shoppinglistapp-9a3df',
    authDomain: 'shoppinglistapp-9a3df.firebaseapp.com',
    storageBucket: 'shoppinglistapp-9a3df.firebasestorage.app',
  );
}